CREATE TABLE IF NOT EXISTS PACIENTES
(ID int(10), NOMBRE varchar(200), APELLIDO varchar(200), DNI varchar(20),
EMAIL varchar(200), FECHA_INGRESO varchar(50));

INSERT INTO PACIENTES (ID,NOMBRE,APELLIDO,DNI,EMAIL,FECHA_INGRESO) VALUES (2,"GASTON","ODETTI"
,"G@MAIL.COM", "HOY");
